spring:
  jpa:
    show-sql: true
  #    对对象的过滤规则：这里设置为不为null的数据返回
  jackson:
    default-property-inclusion: non_null

c3p0:
  jdbcUrl: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  user: root
  password: 123456a!
  driverClass: com.mysql.cj.jdbc.Driver
  minPoolSize: 2
  maxPoolSize: 10
  maxIdleTime: 6000
  breakAfterAcquireFailure: true
  testConnectionOnCheckout: false



